sudo: required
services:
  - docker

before_install:
  - docker build -t abhay/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true abhay/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "DevDockerReact"
  env: "DevDockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-843905125956"
  bucket_path: "DevDockerReact"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"